using CEOS_WebApi.Controllers;
using CEOS_WebApi.Model;
using CEOS_WebApi.Repository;
using Microsoft.AspNetCore.Mvc;
using Moq;

namespace Ceos_WebApi_TEST
{
    public class Tests
    {
        public Mock<IBooksRepository> _mockService;
        public BookController _controller;

        [SetUp]
        public void Setup()
        {
            _mockService = new Mock<IBooksRepository>();
            _controller = new BookController();
        }

        [Test]
        public void Test1()
        {
            // here would be data to compare, but our data are generated by random, so currently cannot match
            var products = new List<Book>();

            _mockService.Setup(x => x.GetBooks())
                .Returns(products);

            var result = _controller.GetBooks();

            Assert.IsNotNull(result);
            Assert.That(result, Is.EqualTo(new JsonResult(products)));
            _mockService.Verify(x=>x.GetBooks(), Times.Once());
        }
    }
}