// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShipsTransportManager.Context;

namespace ShipsTransportManager.Migrations
{
    [DbContext(typeof(STMContext))]
    [Migration("20210212104137_PlanetAddedLanding")]
    partial class PlanetAddedLanding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ShipsTransportManager.Models.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ActuallyDocked")
                        .HasColumnType("int");

                    b.Property<int>("Landing")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShipCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("ShipsTransportManager.Models.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsDocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanetId")
                        .HasColumnType("int");

                    b.Property<double>("WarpSpeed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("ShipsTransportManager.Models.Ship", b =>
                {
                    b.HasOne("ShipsTransportManager.Models.Planet", "Planet")
                        .WithMany("ListOfShips")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planet");
                });

            modelBuilder.Entity("ShipsTransportManager.Models.Planet", b =>
                {
                    b.Navigation("ListOfShips");
                });
#pragma warning restore 612, 618
        }
    }
}
